baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Gilliano Agard | Cloud Security Engineer'
theme = 'PaperMod'

[params]
description = 'Securing Azure environments through Zero Trust architecture, identity governance and automated endpoint compliance.'